.TH ft_readline 3 "13 April 2018" "" "42 Student Lib"
.SH NAME
ft_readline - Read a line from stdin
.SH SYNOPSYS
#include <libftreadline.h>

.nf
.I char *
.fi
.B ft_readline
(const char *prompt, t_rl_opts *opts, t_rl_hist *hist);

.SH DESCRIPTION
.B 
ft_readline()
reads a line from stdin and returns a malloced copy.
You should free the returned result once you are done dealing with it.
It takes a prompt as a C-string, a series of options via a ref
to a
.B t_rl_opts struct
and a ref to the head of a
.B t_rl_hist linked list.

.SH RETURN VALUES
If EOF is catched,
.B ft_readline()
returns NULL. Otherwise, a valid C-string is passed. This string might be empty.
If no input has been typed,
.B ft_readline()
returns a valid C-string only containing the terminating NULL character.

.SH SEE ALSO
Nothing for now

.SH AUTHOR
Copyright kdumarai@ - 2017-2018 - Kelian DUMARAIS
