# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kdumarai <kdumarai@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/07/16 17:49:56 by kdumarai          #+#    #+#              #
#    Updated: 2018/07/17 21:33:37 by kdumarai         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	./compile_readline_tester.sh

fcleanp:
	rm -f ft_readline_tester

rep: fcleanp all

.PHONY: all fcleanp rep
